name: ztunnel
base: ubuntu@24.04
version: '0.1'
summary: Ztunnel provides an implementation of the ztunnel component of ambient mesh
description: |
  Ztunnel is intended to be a purpose built implementation of the node proxy in ambient mesh. Part of the goals of this included keeping a narrow feature set, implementing only the bare minimum requirements for ambient. This ensures the project remains simple and high performance.
platforms:
  amd64:

entrypoint-service: ztunnel
services:
  ztunnel:
    command: /bin/ztunnel [ ]
    override: replace
    startup: enabled

parts:
  build:
    plugin: rust
    source: https://github.com/istio/ztunnel.git
    source-tag: 1.23.3
    rust-channel: 1.79.0
    build-packages:
      - protobuf-compiler
